# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_color_theme: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
url: https://blog.vsccw.com # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: # does not include hostname
title: vsccw's blog
description: > # this means to ignore newlines until "Language & timezone"
  代码、iOS开发、理科男、飞一般的码农


## => Language and Timezone
##############################
lang: "zh" # the language of your site, "en" (default, English), "zh"(简体中文), "zh-Hans"(简体中文), "zh-Hant"(繁體中文)
timezone: Asia/Shanghai # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  name: vsccw
  email: me@vsccw.com # your Email address e.g. someone@site.com
  facebook: qiuncheng55 # your Facebook username
  twitter: vsccw # your Twitter username
  github: qiuncheng # your GitHub username
  linkedin: # your Linkedin username
  googleplus: # your Google+ username
  weibo: qiuncheng # your Weibo username
  douban: # your Douban username


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: qiuncheng/qiuncheng.github.io
repository_tree: master


## => Paths
##############################
paths:
  base: /


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->
excerpt_type: html # text (default), html

## TOC
toc:
  selectors: # "h1,h2,h3" (default)

## Markdown Enhancements

# Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

# Mermaid
mermaid: # false (default), true

# Chart
chart: # false (default), true


## => Paginate
##############################
paginate: 6
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Comments
##############################
## Disqus
disqus:
  shortname: # the Disqus shortname for the site

## Gitalk
# please refer to https://github.com/gitalk/gitalk for more info.
gitalk:
  clientID: "6d529dd5eb1ef80e8215" # GitHub Application Client ID
  clientSecret: "597261a472d78f0d9a12655a468c56621c68b2db" # GitHub Application Client Secret
  repository: "blog-comment" # GitHub repo
  owner: "qiuncheng" # GitHub repo owner
  admin: "qiuncheng" # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
    # - your GitHub Id


## => Pageview
##############################
## Leancloud
leancloud:
  app_id: H9lSXDr9KMU2YnDmIEX1DyBO-gzGzoHsz # LeanCloud App id
  app_key: 2tMgYRtawjotABBgPIWP0XjQ # LeanCloud App key
  app_class: vsccw_blog # LeanCloud App class


## => Analytics
##############################
## Google Analytics
ga_tracking_id: "UA-92177773-1" # Google Analytics id for the site, Format: UA-xxxxxx-xx
ga_anonymize_ip: false # Anonymize IP tracking for Analytics
ga_domain: blog.vsccw.com


## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: :title.html

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      license: true
      aside:
        toc: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji